services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sample
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepass
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_NAME: sample
      DB_USER: sampleuser
      DB_PASSWORD: samplepass
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/var/www/html/src
      - ./web:/var/www/html/web
      - ./dic:/var/www/html/dic
      - ./config-dev:/var/www/html/config-dev
      - ./logs:/var/www/html/logs

volumes:
  db-data:
